// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASukej2z1Cmmk4VOl9S-jMRvyFvCGCx4Q',
    appId: '1:265907686144:web:1340f44513bdf44c8f41e5',
    messagingSenderId: '265907686144',
    projectId: 'predating-a2742',
    authDomain: 'predating-a2742.firebaseapp.com',
    storageBucket: 'predating-a2742.firebasestorage.app',
    measurementId: 'G-7QWHPS76KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEHumu6rn13NIIOIEe5-wCcLH4m63JbE',
    appId: '1:265907686144:android:5a84ad63766d76ca8f41e5',
    messagingSenderId: '265907686144',
    projectId: 'predating-a2742',
    storageBucket: 'predating-a2742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAALg_2ARpXxFlvz8RIiCekb_2kVUtSZoY',
    appId: '1:265907686144:ios:28f04d64c9dc0d258f41e5',
    messagingSenderId: '265907686144',
    projectId: 'predating-a2742',
    storageBucket: 'predating-a2742.firebasestorage.app',
    iosBundleId: 'com.example.tre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAALg_2ARpXxFlvz8RIiCekb_2kVUtSZoY',
    appId: '1:265907686144:ios:28f04d64c9dc0d258f41e5',
    messagingSenderId: '265907686144',
    projectId: 'predating-a2742',
    storageBucket: 'predating-a2742.firebasestorage.app',
    iosBundleId: 'com.example.tre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASukej2z1Cmmk4VOl9S-jMRvyFvCGCx4Q',
    appId: '1:265907686144:web:eada91b6e353d45e8f41e5',
    messagingSenderId: '265907686144',
    projectId: 'predating-a2742',
    authDomain: 'predating-a2742.firebaseapp.com',
    storageBucket: 'predating-a2742.firebasestorage.app',
    measurementId: 'G-03KDSBC8YX',
  );
}
